version: '2'

services:
  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/diaspora

  postgres:
    image: 'kiasaki/alpine-postgres'
    environment:
      POSTGRES_USER: 'diaspora'
      POSTGRES_PASSWORD: 'diaspora'
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis/data

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
